### ISSUE TITLE
Create a matching pipeline as an embedded ScanCode.io pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#238]
The complexity of matching at scale means that we eventually need the pipelining of ScanCode.io to organize code matching, for instance to cascade from exact archive matching to file matching to directory matching to approximate matching.

Furthermore, some disambiguation is only effective when done on the match results across the analyzed codebase or across a directory tree, rather than one file at a time. 

Therefore we should design a ScanCode.io pipeline that has privileged access to  PurlDB. That will be used to in a special SCIO instance and expose a new REST API matching request taking a whole codebase as an input

Some of the solution elements may include:
- [x] A basic matching ScanCode.io pipeline to orchestrate multiple matching steps as coherent steps. This is tracked in #224 for the commits stream.
- [x] A ScanCode.io instance embedded in PurlDB as a library to run this pipeline with a privileged access to the PurlDB database ... tracked here
- [x] A new code matching JSON REST API using this embedded this ScanCode.io, accepting a whole scan as an input. This is tracked in #224 
- [x] A new ScanCode.io "client" pipeline to run code matching on a codebase. This is tracked in https://github.com/nexB/purldb/issues/273 and done in this PR https://github.com/nexB/scancode.io/pull/1042

**Comment by pombredanne** [comment]
See also https://github.com/nexB/purldb/issues/121

**Comment by pombredanne** [comment]
This is completed: See https://github.com/nexB/purldb/issues/273#issuecomment-1968983898 for all details as well as https://github.com/nexB/scancode.io/pull/1042
