### ISSUE TITLE
Feature: purl2sym: Expand support for multiple tools

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#313]
This is to extend the ScanCode.io pipeline in nexB/purldb#312 to support multiple tools, including two pure Python tools, two native tools, as well as collecting symbols from OpenSSL, Busybox, and uCLibc. This includes updating the scanning architecture of PurlDB to accommodate multiple ScanCode.io worker systems (whole machines) and expose a queue API where ScanCode.io instances can pick a scanning job to run symbol collections. A new API endpoint will accept a PURL and return a list of all known PURLs and download URL for all versions of the PURL, and another will provide status on the symbols collections that are pending.

- [x] nexB/scancode.io#1108
  - [x] nexB/source-inspector#2
  - [x] ScanCode.io: https://github.com/nexB/scancode.io/issues/1106
  - [x] nexB/source-inspector#3
  - [x] https://github.com/nexB/scancode.io/issues/1108
- [x] nexB/scancode.io#1107
- [x] nexB/purldb#333
  - [x] nexB/purldb#366
- [x] nexB/purldb#334
- [ ] #388

**Comment by keshav-space** [comment]
We now support native tools like Universal-ctag and xgettext for symbol and string collection. We also support Python tool Pygments and tree-sitter.

The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Go to `/api/collect/` add PURL for indexing. ex: `/api/collect/?purl=pkg:generic/udhcp@0.9.7&addon_pipelines={TOOL_PIPELINE}`
2. Once the indexing has completed go to `/api/resources/`and filter out resource based on PURL to see the symbols and strings for each resource in extra_data field. ex: `/api/resources/?purl=pkg:generic/udhcp@0.9.7`


Replace the `{TOOL_PIPELINE}` in above request with your desired `Pipeline` from the table shown below.  

| Tool  | Pipeline |
| ------------- | ------------- |
| Universal Ctags  | `collect_symbols` |
| Gettext  | `collect_source_strings` |
| Pygments  | `collect_pygments_symbols` |
| Tree-Sitter  | `collect_tree_sitter_symbols` |
